### ISSUE TITLE
Screening.py error

### ISSUE THREAD

**Issue by ArtBioDesign** [CAODH/EquiScore#13]
(equiscore) (base) [yangchh@gnode14 EquiScore]$ python Screening.py --ngpu 1 --test --test_path ./data/sample_data/ --test_name tmp_pockets --pred_save_path  ./data/test_results/EquiScore_pred_for_tmp_pockets.csv
2024-09-24 15:07:57
Available GPU List
id      utilization.gpu(%)      memory.free(MiB)
0       0                       24257           
Select id #0 for you.
load save model!
Process Process-1:
Traceback (most recent call last):
  File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "Screening.py", line 56, in run
    for i_batch, (g,full_g,Y) in enumerate(test_dataloader):
  File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/prefetch_generator/__init__.py", line 116, in next
    raise next_item
  File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/prefetch_generator/__init__.py", line 98, in run
    for item in self.generator: self.queue.put((True , item))
  File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/hpcfs/fhome/yangchh/ai/EquiScore/dataset/dataset.py", line 63, in collate
    g,full_g,Y = map(list, zip(*samples))
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by CAODH** [comment]
> (equiscore) (base) [yangchh@gnode14 EquiScore]$ python Screening.py --ngpu 1 --test --test_path ./data/sample_data/ --test_name tmp_pockets --pred_save_path ./data/test_results/EquiScore_pred_for_tmp_pockets.csv 2024-09-24 15:07:57 Available GPU List id utilization.gpu(%) memory.free(MiB) 0 0 24257 Select id #0 for you. load save model! Process Process-1: Traceback (most recent call last): File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "Screening.py", line 56, in run for i_batch, (g,full_g,Y) in enumerate(test_dataloader): File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/prefetch_generator/**init**.py", line 116, in next raise next_item File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/prefetch_generator/**init**.py", line 98, in run for item in self.generator: self.queue.put((True , item)) File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in **next** data = self._next_data() File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data return self._process_data(data) File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data data.reraise() File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise raise exception ValueError: Caught ValueError in DataLoader worker process 0. Original Traceback (most recent call last): File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "/hpcfs/fhome/yangchh/.conda/envs/equiscore/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch return self.collate_fn(data) File "/hpcfs/fhome/yangchh/ai/EquiScore/dataset/dataset.py", line 63, in collate g,full_g,Y = map(list, zip(*samples)) ValueError: not enough values to unpack (expected 3, got 0)

Maybe the data format doesn't meet the requirements？

**Comment by ArtBioDesign** [comment]
I use the result of "python ./get_pocket/get_pocket.py --docking_result ./data/sample_data/sample_compounds.sdf --recptor_pdb ./data/sample_data/sample_protein.pdb --single_sdf_save_path ./data/sample_data/tmp_sdfs --pocket_save_dir ./data/sample_data/tmp_pockets  ". After,I use "python Screening.py --ngpu 1 --test --test_path ./data/sample_data/ --test_name tmp_pockets --pred_save_path ./data/test_results/EquiScore_pred_for_tmp_pockets.csv".Error,"ValueError: not enough values to unpack (expected 3, got 0)"

**Comment by ArtBioDesign** [comment]
![image](https://github.com/user-attachments/assets/0e296050-40ce-415c-93e1-74e035c39f7d)
