### ISSUE TITLE
lmdb.Error: ./lmdbs/PDBscreen: No such file or directory

### ISSUE THREAD

**Issue by chentong456** [CAODH/EquiScore#3]
```
Process Process-1:
Traceback (most recent call last):
File "/home/chentong/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/home/chentong/anaconda3/envs/pytorch/lib/python3.9/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/mnt/d/papaer_share/EquiScore/train.py", line 92, in run
train_dataset = ESDataset(train_keys,args, args.data_path,args.debug)#keys,args, data_dir,debug
File "/mnt/d/papaer_share/EquiScore/dataset/dataset.py", line 45, in __init__
env = lmdb.open(args.lmdb_cache, map_size=int(1e12), max_dbs=2, readonly=True)
lmdb.Error: ./lmdbs/PDBscreen: No such file or directory

```
how can I get the Folder containing trainging data in lmdb format

**Comment by CAODH** [comment]
你可以检查一下文件路径问题，你是否已经通过邮件问过我相关问题，如果可以的话，请在这里提问，方便大家遇到相同问题可以参考。（You can check the file path problem, whether you have asked me about it through email, if possible, please ask here, so that everyone can refer to the same problem.）

**Comment by chentong456** [comment]
就是没有这个路径，但是我不知道这个路径里面的数据是什么，以及如何创建

**Comment by CAODH** [comment]
你打开test参数 ，python train.py --ngpu 1 --test --train_keys your_keys_path --val_keys your_keys_path --test_keys your_keys_path ,应该就行了，不过这样会很慢，推荐你根据readme提供的方案，先预处理数据集到LMDB

**Comment by Mengo-ye** [comment]
你好，想请教下如何准备这个文件`./lmdbs/PDBscreen`，谢谢。
