### ISSUE TITLE
Cannot import torch

### ISSUE THREAD

**Issue by sunjh22** [CAODH/EquiScore#9]
I followed exactly the same instructions in README to install packages in conda env. But I found the very first step has error:
`
Traceback (most recent call last):
  File "Screening.py", line 2, in <module>
    import utils.utils as utils
  File "/ubda/home/19044464r/project/Huige/EquiScore/utils/utils.py", line 2, in <module>
    import torch
  File "/ubda/home/19044464r/mambaforge/envs/EquiScore/lib/python3.8/site-packages/torch/__init__.py", line 199, in <module>
    from torch._C import *  # noqa: F403
ImportError: /ubda/home/19044464r/mambaforge/envs/EquiScore/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
`
Is it the problem of conflict of package versions?

Best,
Jiahong

**Comment by sunjh22** [comment]
I tried the one from zenodo, and `import torch` worked.
